### ISSUE TITLE
OUTDATED

### ISSUE THREAD

**Issue by ChristianGerlin** [lorenzobenvenuti/strava-cli#15]
This repository is probably outdated. Thanks for the dev for creating it and uploading it to GitHub!

Trying to login gives the following errors:
'Traceback (most recent call last):
  File "/home/christian/gits/strava-cli/./strava-cli.py", line 3, in <module>
    import auth
  File "/home/christian/gits/strava-cli/auth.py", line 5, in <module>
    from flask import Flask, redirect, request, abort
  File "/home/christian/.local/lib/python3.11/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/home/christian/.local/lib/python3.11/site-packages/jinja2/__init__.py)'

**Comment by lorenzobenvenuti** [comment]
For some reason Flask 1.1.2 is installing incompatible versions of transitive dependencies; I'll try to bump everything to the latest versions at some point, but for now I've just pinned transitive dependencies to an older version. I've tried to run the application on a fresh virtual environment and it seems to work.

Thanks,

lorenzo

**Comment by ChristianGerlin** [comment]
Wow this was quick! Thanks.
